name: homy_book
description: Homy Book — personal finance application to track daily expense, budget, goal, and investment.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  fl_chart: ^0.66.2
  flutter_lints: ^4.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
